@echo off
powershell write-host -fore Red "SPO Setup Install Instructions"
powershell write-host -fore Red "-----------------------------------------"
powershell write-host -fore Red "    1. Copy LIVE EFT to New Folder."
powershell write-host -fore Red "    2. Copy SPO-Updater Launcher into New Folder."
powershell write-host -fore Red "    3. DO NOT INSTALL AKI OR PATCHES"
powershell write-host -fore Red "    4. Run Launcher"
powershell write-host -fore Red "    5. Click Start Server"
powershell write-host -fore Red "    6. Wait for Server to Start"
powershell write-host -fore Red "    7. Enjoy SPO"
powershell write-host -fore Red "-----------------------------------------"
powershell write-host -fore Red "If you cannot follow the above instructions no help will be given."
powershell write-host -fore Red "Yes I am talking to you because you did not follow instructions."
powershell write-host -fore Red "-----------------------------------------"
